name: vortex_pro
description: "Vortex Premium OS - Enterprise Edition. Sistema de acceso seguro con integración Cloud."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Motor de peticiones para EmailJS y SQLite Cloud
  http: ^1.2.0
  
  # Tipografías profesionales
  google_fonts: ^6.2.1
  
  # Iconos adicionales
  cupertino_icons: ^1.0.8

  # Para persistencia local
  shared_preferences: ^2.2.2

  # --- LIBRERÍA PARA EL VIDEO ---
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- REGISTRO DE TUS VIDEOS ---
  # Asegúrate de que el video esté en esta carpeta en tu GitHub
  assets:
    - assets/videos/intro.mp4
