name: vortex_pro
description: Vortex Ultimate Premium Full Edition
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  intl: ^0.19.0
  http: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/vortex.mp4
